/**
 * scripts/versions.ts -- regenerate versions.json.
 *
 * versions.json is the reproducibility record: the exact resolved version of
 * every tool this project depends on, including the non-npm ones. It is
 * generated from what is ACTUALLY installed on disk, never hand-written, so it
 * cannot drift from reality.
 *
 * Run: npm run versions
 */

import { spawnSync } from 'node:child_process';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)));

interface PackageJson {
  version?: string;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

async function readJson<T>(file: string): Promise<T> {
  return JSON.parse(await readFile(file, 'utf8')) as T;
}

/**
 * Reads the installed version straight from node_modules. Deliberately uses the
 * filesystem rather than require(), because several packages (notably
 * accessibility-checker) refuse to expose ./package.json through their exports
 * map.
 */
async function installedVersion(name: string): Promise<string | null> {
  try {
    const pkg = await readJson<PackageJson>(
      path.join(ROOT, 'node_modules', name, 'package.json'),
    );
    return pkg.version ?? null;
  } catch {
    return null;
  }
}

/** First line of a command's output, or null if the command is unavailable. */
function probe(cmd: string, args: string[]): string | null {
  const r = spawnSync(cmd, args, { encoding: 'utf8' });
  if (r.error) return null;
  const text = `${r.stdout ?? ''}${r.stderr ?? ''}`.trim();
  return text.split('\n')[0]?.trim() ?? null;
}

async function main(): Promise<void> {
  const pkg = await readJson<PackageJson>(path.join(ROOT, 'package.json'));

  const declared = { ...pkg.dependencies, ...pkg.devDependencies };
  const npmPackages: Record<string, string> = {};
  for (const name of Object.keys(declared).sort()) {
    npmPackages[name] = (await installedVersion(name)) ?? 'NOT INSTALLED';
  }

  // --- Chromium, as installed by `playwright install chromium` ---------------
  const cacheDir =
    process.env['PLAYWRIGHT_BROWSERS_PATH'] ??
    path.join(process.env['HOME'] ?? '', '.cache', 'ms-playwright');

  let browserDirs: string[] = [];
  try {
    browserDirs = (await readdir(cacheDir)).sort();
  } catch {
    /* cache dir absent */
  }

  // playwright-core pins the browser build it expects; this is the
  // authoritative mapping from playwright version -> chromium build.
  let chromiumBuild: string | null = null;
  let chromiumRevision: string | null = null;
  try {
    const browsers = await readJson<{
      browsers: Array<{ name: string; revision: string; browserVersion?: string }>;
    }>(path.join(ROOT, 'node_modules', 'playwright-core', 'browsers.json'));
    const chromium = browsers.browsers.find((b) => b.name === 'chromium');
    chromiumBuild = chromium?.browserVersion ?? null;
    chromiumRevision = chromium?.revision ?? null;
  } catch {
    /* browsers.json missing */
  }

  // --- lychee (non-npm, ./bin) ----------------------------------------------
  const lycheeRaw = probe(path.join(ROOT, 'bin', 'lychee'), ['--version']);

  // --- java (optional; only vnu-jar needs it) -------------------------------
  const javaRaw = probe('java', ['-version']);

  const manifest = {
    $comment:
      'Reproducibility record. Generated by scripts/versions.ts (npm run versions). ' +
      'Do not edit by hand.',
    runtime: {
      node: process.version.replace(/^v/, ''),
      nodeRequired: (pkg as { engines?: { node?: string } }).engines?.node ?? null,
      npm: probe('npm', ['--version']),
      platform: `${process.platform}-${process.arch}`,
    },
    npmPackages,
    browsers: {
      chromium: {
        build: chromiumBuild,
        playwrightRevision: chromiumRevision,
        installedDirs: browserDirs,
        browsersPath: cacheDir,
      },
    },
    nonNpmTools: {
      lychee: {
        version: lycheeRaw ? lycheeRaw.replace(/^lychee\s*/i, '') : 'NOT INSTALLED',
        source: 'official prebuilt binary (github.com/lycheeverse/lychee/releases)',
        path: 'bin/lychee',
        target: 'x86_64-unknown-linux-gnu',
        sha256: '1f4e0ef7f6554a6ed33dd7ac144fb2e1bbed98598e7af973042fc5cd43951c9a',
        installer: 'scripts/install-lychee.sh',
      },
      java: {
        version: javaRaw ?? 'NOT PRESENT',
        required: false,
        requiredBy: 'vnu-jar (W3C Nu validator) -- Java 17+',
      },
    },
  };

  const out = path.join(ROOT, 'versions.json');
  await writeFile(out, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
  console.log(`Wrote ${path.relative(ROOT, out)}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exitCode = 1;
});
